# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadUpdate.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadUpdate(object):
    def setupUi(self, LoadUpdate):
        LoadUpdate.setObjectName("LoadUpdate")
        LoadUpdate.resize(604, 136)
        self.centralwidget = QtWidgets.QWidget(LoadUpdate)
        self.centralwidget.setObjectName("centralwidget")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setGeometry(QtCore.QRect(20, 10, 571, 111))
        self.dropShadowFrame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(255, 170, 255);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_description = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_description.setGeometry(QtCore.QRect(120, 0, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(20, 40, 551, 31))
        self.progressBar.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(250, 75, 101, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        LoadUpdate.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoadUpdate)
        QtCore.QMetaObject.connectSlotsByName(LoadUpdate)

    def retranslateUi(self, LoadUpdate):
        _translate = QtCore.QCoreApplication.translate
        LoadUpdate.setWindowTitle(_translate("LoadUpdate", "MainWindow"))
        self.label_description.setText(_translate("LoadUpdate", "<strong>APP</strong> DESCRIPTION"))
        self.label_loading.setText(_translate("LoadUpdate", "loading..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadUpdate = QtWidgets.QMainWindow()
    ui = Ui_LoadUpdate()
    ui.setupUi(LoadUpdate)
    LoadUpdate.show()
    sys.exit(app.exec_())
