# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LoadDisplay(object):
    def setupUi(self, LoadDisplay):
        LoadDisplay.setObjectName("LoadDisplay")
        LoadDisplay.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(LoadDisplay)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(255, 255, 0);\n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_title.setGeometry(QtCore.QRect(0, 40, 661, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(254, 121, 199);")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_description = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_description.setGeometry(QtCore.QRect(-10, 130, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(50, 260, 561, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(9, 9, 9);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.511364, x2:1, y2:0.523, stop:0 rgba(254, 121, 199, 255), stop:1 rgba(170, 85, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 5)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(2, 300, 657, 32))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_credits = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_credits.setGeometry(QtCore.QRect(480, 348, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.lineEdit = QtWidgets.QLineEdit(self.dropShadowFrame)
        self.lineEdit.setGeometry(QtCore.QRect(210, 200, 171, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setToolTipDuration(-1)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.dropShadowFrame)
        self.pushButton.setGeometry(QtCore.QRect(382, 200, 101, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"")
        self.pushButton.setShortcut("")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.version = QtWidgets.QLabel(self.dropShadowFrame)
        self.version.setGeometry(QtCore.QRect(20, 350, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.version.setFont(font)
        self.version.setStyleSheet("color: rgb(255, 0, 0);")
        self.version.setText("")
        self.version.setObjectName("version")
        self.toolButton = QtWidgets.QToolButton(self.dropShadowFrame)
        self.toolButton.setGeometry(QtCore.QRect(627, 0, 34, 31))
        self.toolButton.setStyleSheet("QToolButton {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius: 10px;\n"
"}")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.label_2 = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(True)
        self.label_2.setStyleSheet("color: rgb(255, 85, 255);")
        self.label_2.setLineWidth(1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        LoadDisplay.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoadDisplay)
        QtCore.QMetaObject.connectSlotsByName(LoadDisplay)

    def retranslateUi(self, LoadDisplay):
        _translate = QtCore.QCoreApplication.translate
        LoadDisplay.setWindowTitle(_translate("LoadDisplay", "MainWindow"))
        self.label_title.setText(_translate("LoadDisplay", "<html><head/><body><p>GOM LUA</p><p><br/></p></body></html>"))
        self.label_description.setText(_translate("LoadDisplay", "<strong>APP</strong> DESCRIPTION"))
        self.label_loading.setText(_translate("LoadDisplay", "loading..."))
        self.label_credits.setText(_translate("LoadDisplay", "<html><head/><body><p><span style=\" font-weight:600;\">Created</span>: Công Danh</p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("LoadDisplay", "Nhập key tool"))
        self.pushButton.setText(_translate("LoadDisplay", "Đăng nhập"))
        self.label_2.setText(_translate("LoadDisplay", "Tele: @DanhNguyenn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadDisplay = QtWidgets.QMainWindow()
    ui = LoadDisplay()
    ui.setupUi(LoadDisplay)
    LoadDisplay.show()
    sys.exit(app.exec_())
